I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 192, in script
    python:
  File "renpy/common/00start.rpy", line 193, in <module>
    renpy.execute_default_statement(True)
  File "game/script.rpy", line 4, in set_default
    default blink_timer_c = renpy.random.randint(3, )
  File "game/script.rpy", line 4, in <module>
    default blink_timer_c = renpy.random.randint(3, )
TypeError: randint() takes exactly 3 arguments (2 given)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 192, in script
    python:
  File "renpy/ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00start.rpy", line 193, in <module>
    renpy.execute_default_statement(True)
  File "renpy/exports.py", line 3797, in execute_default_statement
    i.set_default(start)
  File "game/script.rpy", line 4, in set_default
    default blink_timer_c = renpy.random.randint(3, )
  File "renpy/python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 4, in <module>
    default blink_timer_c = renpy.random.randint(3, )
TypeError: randint() takes exactly 3 arguments (2 given)

Windows-10-10.0.19041 AMD64
Ren'Py 7.5.3.22090809
test01 1.0
Sat Jan 28 15:57:35 2023
